### PR TITLE
add github actions

### PR DESCRIPTION
**Pull request by huppd**
- adds github actions, which checks formatting on every push to master and pull request
- removes formatter jenkins file, as they are obsolete with github actions

### CODE REVIEW

**Comment by huppd** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
yes please

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkin

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Review by faeglas — APPROVED** [review]
Looks good.

**Pull request merged**
