### PR TITLE
Rm g110 dependencies

### PR DESCRIPTION
**Pull request by huppd**
- remove g110 dependencies
- remove code dublication

### CODE REVIEW

**Comment by stelliom** [comment]
Everything looks pretty straightforward to me. I also couldn't find any typos or small errors, so I'd say this is ready for merging.

My only question is: why did you remove the three wrappers? Are they just not used anymore or is there another reason?

**Comment by huppd** [comment]
> Everything looks pretty straightforward to me. I also couldn't find any typos or small errors, so I'd say this is ready for merging.
> 
> My only question is: why did you remove the three wrappers? Are they just not used anymore or is there another reason?

Thanks for the review. From my understanding these wrappers were used to generate testing references for probtest. They are replicated part of the BB infrastructure.
But we changed the approach to be more platform and ICON independent so that they shouldn't be needed anymore.

**Comment by stelliom** [comment]
I see, all good then 👍

**Review by stelliom — APPROVED** [review]
All good!

**Pull request merged**
